
spring:
  application:
    name: ${APP_NAME:producer-application}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      topic: ${KAFKA_TOPIC_NAME:test}

server:
  port: 8080
