spring:
  application:
    name: ${APP_NAME:consumer-application}
  kafka:
    auto-offset-reset: latest
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    group-id: consumer-group
    topic:
      name: ${KAFKA_TOPIC_NAME:test}

server:
  port: 8081